version: '3'
services:
  drupal:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    restart: always
    environment:
      MYSQL_CONNSTR: drupalgaef:europe-west1:gglewdevdrgaefsql01
      MYSQL_DATABASE: drupal
      MYSQL_USER: root
      MYSQL_PW: U3zaSep6
